### ISSUE TITLE
企業/入力フォームに不要な空白文字が挿入されているように見える

### ISSUE THREAD

**Issue by mickhosokawa** [mickhosokawa/seek#21]
1つ目の入力フォームを修正中です。
なぜか文字が中央寄り？、先頭と語尾に余計な空白が入ってしまっています。
Email address, URLは余白が入っていないのに、他の入力項目では全て入ってしまっています。
html, cssの記載は全て同じなのですが、どうしてこのような現象が起きるのでしょうか？
stype_space()で空白文字があるか調べてみたのですが、結果はfalseでした。

**Comment by aokitashipro** [comment]
確認しまして、value=“” の中に空白が入ってるとその分開いちゃいますね。if文などで判定かけてるんですが改行などをしている分空いてしまうので、 ちと読みづらくなりますが詰め詰めで書いていただければと思います。 {{}} の中の空白は影響なしです。
