### ISSUE TITLE
企業/求人情報編集

### ISSUE THREAD

**Issue by aokitashipro** [mickhosokawa/seek#6]

**Comment by mickhosokawa** [comment]
投稿済みの求人情報を編集・削除する機能を作成します。
【対象ファイル】
PostedJobOfferController.php
resource/company/jobs/edit.blade.php(new)
【流れ】
求人情報編集画面に、選択した求人番号の求人情報を表示させる
全ての項目を編集可能にする
編集しない項目は更新しない
更新が完了したらフラッシュメッセージを表示する
